FROM deepfabric/build as builder

COPY . /root/go/src/github.com/matrixorigin/matrixcube
WORKDIR /root/go/src/github.com/matrixorigin/matrixcube

RUN make redis

FROM deepfabric/centos
COPY --from=builder /root/go/src/github.com/matrixorigin/matrixcube/dist/redis /usr/local/bin/redis

ENTRYPOINT ["/usr/local/bin/redis"]
